#!/usr/bin/env python3
"""Reassemble Letters for Titles from blog posts into book order.

The site is a WordPress blog, so it presents newest-first and scatters the
work across 262 permalinks. The work itself is a book: 15 chapters that
read the Rune Poem inward from both ends. This rebuilds it.

Outputs:
  book/reading-order.md  the whole book in its intended sequence, chapter by
                         chapter, each post in publication order
  book/poem-order.md     the alternate cut: stanzas 1-29 in futhorc order,
                         each with its rune, casting, translation and chapter

Usage:  python3 tools/book.py
"""
import argparse, collections, json, os, re, sys

# The Old English Rune Poem's 29 runes, in manuscript order. Stanza N is
# rune N; the site's chapters pair stanza N with stanza 30-N.
FUTHORC = [
    ("Feoh", "ᚠ"), ("Ur", "ᚢ"), ("Thorn", "Þ"), ("Os", "ᚩ"), ("Rad", "ᚱ"),
    ("Cen", "ᚳ"), ("Gifu", "ᚷ"), ("Wyn", "ᚹ"), ("Hægl", "ᚻ"), ("Nyd", "ᚾ"),
    ("Is", "ᛁ"), ("Ger", "ᛄ"), ("Eoh", "ᛇ"), ("Peorþ", "ᛈ"), ("Eolhx", "ᛉ"),
    ("Sigel", "ᛋ"), ("Tiw", "ᛏ"), ("Beorc", "ᛒ"), ("Eh", "ᛖ"), ("Mann", "ᛗ"),
    ("Lagu", "ᛚ"), ("Ing", "ᛝ"), ("Eþel", "ᛟ"), ("Dæg", "ᛞ"), ("Ac", "ᚪ"),
    ("Æsc", "ᚫ"), ("Yr", "ᚣ"), ("Ior", "ᛡ"), ("Ear", "ᛠ"),
]

ROLE_LABEL = {
    "stanza": "stanza", "translating": "translation", "casting": "rune casting",
    "glyph": "rune", "howto": "how-to", "isfor": "alphabet", "xyz": "X≠Y≠Z",
    "other": "",
}


def role_of(title):
    if re.match(r"^Stanza \d+:", title):
        return "stanza"
    if re.match(r"^Translating\b", title):
        return "translating"
    if title.startswith("Rune Casting"):
        return "casting"
    if re.match(r"^How [Tt]o\b", title):
        return "howto"
    if re.match(r"^X ?≠ ?Y ?≠ ?Z", title):
        return "xyz"
    if " is for " in title:
        return "isfor"
    if len(title) <= 3 and not title.isascii():
        return "glyph"
    return "other"


def chapters_in_order(recs):
    by = collections.defaultdict(list)
    for r in recs:
        for c in r["categories"]:
            by[c].append(r)
    for c in by:
        by[c].sort(key=lambda r: (r["date"], r["id"]))
    return sorted(by.items(), key=lambda kv: kv[1][0]["date"])


def thumb_map(manifest_path):
    """Full-resolution image URL -> archived thumbnail path, if archived."""
    if not os.path.exists(manifest_path):
        return {}
    man = json.load(open(manifest_path))
    return {e["url"]: "archive/thumbs/" + e["file"] for e in man.get("images", [])}


def stanza_numbers(recs):
    out = {}
    for r in recs:
        m = re.match(r"^Stanza (\d+):\s*(.+)$", r["title"])
        if m:
            out[int(m.group(1))] = (m.group(2), r)
    return out


def write_reading_order(recs, thumbs, path):
    chaps = chapters_in_order(recs)
    st = stanza_numbers(recs)
    chap_stanzas = collections.defaultdict(list)
    for n, (_, r) in st.items():
        if r["categories"]:
            chap_stanzas[r["categories"][0]].append(n)

    L = ["# Letters for Titles",
         "",
         "Vern Tonkin — <https://www.lettersfortitles.com>",
         "",
         "Reassembled into book order from 262 blog posts. Chapters run in the",
         "order they were published, which is the order the work is meant to be",
         "read: the Rune Poem taken from both ends inward, stanza *n* paired with",
         "stanza *30−n*, converging on the unpaired stanza 15.",
         "",
         "Generated by `tools/book.py` from `data/corpus.json`.",
         "", "---", ""]

    for i, (chap, posts) in enumerate(chaps):
        nums = sorted(chap_stanzas.get(chap, []))
        if nums:
            gloss = " + ".join(f"stanza {n} ({st[n][0]}, {FUTHORC[n-1][1]} {FUTHORC[n-1][0]})"
                               for n in nums)
            head = f"## {chap}\n\n*{gloss}*"
        else:
            head = f"## {chap}\n\n*front matter*"
        L += [head, "", f"{len(posts)} posts, {posts[0]['date']} – {posts[-1]['date']}", ""]

        for r in posts:
            lab = ROLE_LABEL[role_of(r["title"])]
            suffix = f"  ·  *{lab}*" if lab else ""
            L += [f"### {r['title']}", "",
                  f"{r['date']}{suffix}  ·  [source]({r['link']})", ""]
            for u in r["image_urls"]:
                t = thumbs.get(u)
                L.append(f"![{r['title']}]({t})" if t else f"<{u}>")
            if r["image_urls"]:
                L.append("")
            for para in r.get("paragraphs") or ([r["text"]] if r["text"] else []):
                L += [para, ""]
        L += ["---", ""]

    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    open(path, "w").write("\n".join(L))
    return len(chaps)


def write_poem_order(recs, path):
    st = stanza_numbers(recs)
    by_title = {r["title"]: r for r in recs}
    L = ["# The Rune Poem in futhorc order",
         "",
         "The book reads the poem inward from both ends. This is the other cut:",
         "all 29 stanzas in manuscript order, each with the posts that work it out.",
         "",
         "Generated by `tools/book.py`.",
         "",
         "| # | Rune | Name | Tonkin's gloss | Chapter | Casting | Translation |",
         "|---|---|---|---|---|---|---|"]

    for n, (name, glyph) in enumerate(FUTHORC, 1):
        gloss, rec = st.get(n, ("—", None))
        chap = rec["categories"][0] if rec and rec["categories"] else "—"
        cast = next((t for t in by_title if t.startswith("Rune Casting")
                     and t.split(":")[-1].strip().lower() == name.lower()), None)
        tran = next((t for t in by_title if t.startswith("Translating")
                     and t.split(None, 1)[-1].strip().lower().rstrip("ð þ") ==
                     name.lower().rstrip("ð þ")), None)
        link = lambda t: f"[{t}]({by_title[t]['link']})" if t else "—"
        L.append(f"| {n} | {glyph} | {name} | {gloss} | {chap} | "
                 f"{link(cast)} | {link(tran)} |")

    L += ["", "Stanza 15 (Eolhx) is the poem's midpoint and the book's endpoint.",
          "Its name appears nowhere else in Old English and cannot be translated.", ""]
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    open(path, "w").write("\n".join(L))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--corpus", default="data/corpus.json")
    ap.add_argument("--manifest", default="data/media.json")
    ap.add_argument("--out-dir", default="book")
    args = ap.parse_args()

    recs = json.load(open(args.corpus))
    thumbs = thumb_map(args.manifest)
    n = write_reading_order(recs, thumbs, os.path.join(args.out_dir, "reading-order.md"))
    write_poem_order(recs, os.path.join(args.out_dir, "poem-order.md"))
    print(f"wrote {n} chapters and the 29-stanza table to {args.out_dir}/",
          file=sys.stderr)


if __name__ == "__main__":
    main()
